logging:
  level:
    com.seatliberator.seatliberator.jwks: debug

identity:
  jwks:
    signable-kid: "key-20260308-214814"
    keys:
      - kid: "key-20260308-214814"
        private-key: "classpath:keys/key-20260308-214814/private.pem"
        public-key: "classpath:keys/key-20260308-214814/public.pem"
      - kid: "key-20260308-214756"
        private-key: "classpath:keys/key-20260308-214756/private.pem"
        public-key: "classpath:keys/key-20260308-214756/public.pem"

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
      dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_SCHEMA}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            scope: read:user, user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/github"
            client-name: GitHub
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope: openid, profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
            client-name: Google
