spring:
  datasource:
    url: jdbc:postgresql://upseul.mooo.com:5432/seatliberator
    username: Odyz
    password: dheltpdntm
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect