identity:
  starter:
    security:
      jwk-set-uri: ${JWKS_BASE_URL:http://localhost:8080}/.well-known/jwks.json

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: ${DB_DIALECT}
